In [1]:
import numpy as np

# Métodos implementados

In [15]:
def gauss_jacobi(A,B, x0=None, maxiter=100, tol=1e-8):
  C,g = A.copy(), B.copy()
  n = len(A)
  if x0 is None:
    x = np.zeros((n,1))
  else:
    x = x0.copy()
  X = [x]

  def dr(x_new,x):
    return np.max(np.abs(x_new - x)) / np.max(np.abs(x_new))

  for i in range(n):
    C[i] = -A[i]/A[i,i]
    C[i,i] = 0
    g[i] = B[i]/A[i,i]

  for _ in range(maxiter):
    x = C @ X[-1] + g
    X.append(x)

    if dr(X[-1], X[-2]) < tol:
      break

  return np.array(X)

In [14]:
def gauss_seidel(A,B, maxiter=100, tol=1e-8):
  C,g = A.copy(), B.copy()
  n = len(A)
  X = [np.zeros((n,1))]

  def dr(x_new,x):
    return np.max(np.abs(x_new - x)) / np.max(np.abs(x_new))

  for i in range(n):
    C[i] = -A[i]/A[i,i]
    C[i,i] = 0
    g[i] = B[i]/A[i,i]

  for _ in range(maxiter):
    x = X[-1].copy()
    for i in range(n):
      x[i] = C[i] @ x + g[i]
    X.append(x)

    if dr(X[-1], X[-2]) < tol:
      break

  return np.array(X)

In [4]:
def lines_criteria(matrix):
  diagonal = np.diag(matrix)
  row_sums = np.sum(matrix, axis=1) - diagonal
  return diagonal > row_sums

In [23]:
def sassenfeld_criteria(M):
  n = len(M)
  B = np.ones(n)
  for j in range(n):
    B[j] = sum(np.abs(M[j,i])*B[i] for i in range(n) if i != j)  / np.abs(M[j,j])

  return np.max(B)

# 1 – Considere o seguinte sistema:

$$-3x_1 + x_2 + x_3 = 2$$

$$2x_1 + 5x_2 + x_3 = 5$$

$$2x_1 + 3x_2 + 7x_3 = -17$$

## a) Usando o método de Gauss-Jacobi, com aproximação inicial $x^1 = (1,1,-1)$, desenvolva o algoritmo para obter a convergência do método e determinar  as soluções. Cheque a obtenção dos seguintes resultados.

In [10]:
A = np.array([
    [-3,1,1],
    [2,5,1],
    [2,3,7]
], dtype='float')

B = np.array([
    [2],
    [5],
    [-17]
], dtype='float')

x0 = np.array([1,1,-1], dtype='float').reshape(-1,1)

In [20]:
x = gauss_jacobi(A, B, x0)
x

array([[[ 1.        ],
        [ 1.        ],
        [-1.        ]],

       [[-0.66666667],
        [ 0.8       ],
        [-3.14285714]],

       [[-1.44761905],
        [ 1.8952381 ],
        [-2.58095238]],

       [[-0.8952381 ],
        [ 2.0952381 ],
        [-2.82721088]],

       [[-0.9106576 ],
        [ 1.92353741],
        [-3.0707483 ]],

       [[-1.04907029],
        [ 1.9784127 ],
        [-2.99275672]],

       [[-1.00478134],
        [ 2.01817946],
        [-2.97672822]],

       [[-0.98618292],
        [ 1.99725818],
        [-3.0064251 ]],

       [[-1.00305564],
        [ 1.99575819],
        [-3.00277267]],

       [[-1.00233816],
        [ 2.00177679],
        [-2.99730904]],

       [[-0.99851075],
        [ 2.00039707],
        [-3.00009344]],

       [[-0.99989879],
        [ 1.99942299],
        [-3.00059567]],

       [[-1.0003909 ],
        [ 2.00007865],
        [-2.99978163]],

       [[-0.99990099],
        [ 2.00011268],
        [-2.99992202]],

      

## b) Refaça o item anterior, aplicando o método de Gauss-Seidel

In [19]:
x = gauss_seidel(A,B)
x

array([[[ 0.        ],
        [ 0.        ],
        [ 0.        ]],

       [[-0.66666667],
        [ 1.26666667],
        [-2.78095238]],

       [[-1.17142857],
        [ 2.0247619 ],
        [-2.96163265]],

       [[-0.97895692],
        [ 1.9839093 ],
        [-2.99911629]],

       [[-1.005069  ],
        [ 2.00185086],
        [-2.99934494]],

       [[-0.99916469],
        [ 1.99953487],
        [-3.00003932]],

       [[-1.00016815],
        [ 2.00007512],
        [-2.99998415]],

       [[-0.99996968],
        [ 1.9999847 ],
        [-3.00000211]],

       [[-1.0000058 ],
        [ 2.00000274],
        [-2.99999952]],

       [[-0.99999893],
        [ 1.99999947],
        [-3.00000008]],

       [[-1.0000002 ],
        [ 2.0000001 ],
        [-2.99999998]],

       [[-0.99999996],
        [ 1.99999998],
        [-3.        ]],

       [[-1.00000001],
        [ 2.        ],
        [-3.        ]],

       [[-1.        ],
        [ 2.        ],
        [-3.        ]]])

## c) Cheque a obtenção de convergência através do critério das linhas e do critério de Sassenfeld.

In [21]:
lines_criteria(A)

array([False,  True,  True])

In [24]:
sassenfeld_criteria(A)

0.6666666666666666

# 2 – Resolva o sistema

$$
\begin{cases}
10x + y = 23 \\
x + 8y = 26
\end{cases}
$$

Usando o método de Gauss-Seidel com condições iniciais $x^1 = y^1 = 0$

Verifique, ao executar o algoritmo, a obtenção da seguinte evolução:

In [27]:
A = np.array([
    [10,1],
    [1,8]
], dtype='float')

B = np.array([
    [23],
    [26]
], dtype='float')

In [28]:
x = gauss_seidel(A,B)
x

array([[[0.        ],
        [0.        ]],

       [[2.3       ],
        [2.9625    ]],

       [[2.00375   ],
        [2.99953125]],

       [[2.00004687],
        [2.99999414]],

       [[2.00000059],
        [2.99999993]],

       [[2.00000001],
        [3.        ]],

       [[2.        ],
        [3.        ]]])