In [1]:
import numpy as np
import matplotlib.pyplot as plt

# 1 – Escreva o código de uma função que resolve um sistema linear triangular inferior com as substituições sucessivas.

Parâmetros de entrada: matriz A e vetor b;

Saída: vetor x


In [ ]:
def lower_triangular(A: np.ndarray, b: np.ndarray):
  A = A.copy()
  b = b.copy()
  M = np.c_[A,b]
  n = A.shape[0]
  for i in range(n):
    pivot = M[i,i]
    pivot_row = M[i]
    column = M[i+1:, i]
    coef = column/pivot
    M[i+1:] -= coef[:, np.newaxis]*pivot_row

  return M[:, :3], M[:, 3]

In [ ]:
def solve_system_ti(A,b):
  n = len(b)
  b_cp = b.copy()
  x = np.zeros(n)
  for i in range(n):
    for j in range(0, i):
      b_cp[i] -= x[j]*A[i,j]
    x[i] = b_cp[i]/A[i,i]
    # x[i] = (b[i] - np.sum(x[:i] * A[i,:i])) / A[i,i]

  return x

In [11]:
A = np.array([[.3, .52, 1], [.5, 1, 1.9], [.1, .3, .5]])
B = np.array([-0.01, 0.67, -0.44]).reshape(3,1)
solve_system_ti(A,B)

array([-0.03333333,  0.68666667, -1.28533333])

# 2 - Escreva o código de uma função que resolve um sistema linear triangular superior com as substituições sucessivas.

Parâmetros de entrada: matriz A e vetor b;

Saída: vetor x

In [ ]:
def upper_triangular(A: np.ndarray, b: np.ndarray):
  A = A.copy()
  b = b.copy()
  M = np.c_[A,b]
  n = A.shape[0]
  for i in reversed(range(n)):
    pivot = M[i,i]
    pivot_row = M[i]
    column = M[:i, i]
    coef = column/pivot
    M[:i] -= coef[:, np.newaxis]*pivot_row

  return M[:, :3], M[:, 3]

In [4]:
def solve_system_ts(A,b):
  n = len(b)
  b_cp = b.copy()
  x = np.zeros(n)
  for i in reversed(range(n)):
    for j in range(i+1, n):
      b_cp[i] -= x[j]*A[i,j]
    x[i] = b_cp[i]/A[i,i]
    # x[i] = (b[i] - np.sum(x[i+1:] * A[i,i+1:])) / A[i,i]

  return x

In [12]:
A = np.array([[.3, .52, 1], [.5, 1, 1.9], [.1, .3, .5]])
B = np.array([-0.01, 0.67, -0.44]).reshape(3,1)
solve_system_ts(A,B)

array([-1.15946667,  2.342     , -0.88      ])

# 3 – Aplique o Método da Eliminação de Gauss para resolver o seguinte sistema:

$$x + y + z = 1$$

$$4x + 4y + 2z = 2$$

$$2x + y - z = 0$$

Dica: obtenha a matriz estendida do sistema

In [9]:
def gauss_elimination(A, B):
  n = len(A)
  A_cp = A.copy()
  B_cp = B.copy()

  for i in range(n-1):
    pivot = A_cp[i,i]

    for j in range(i+1, n):
      m = (-1)*A_cp[j,i]/A_cp[i,i]
      A_cp[j,:] += A_cp[i,:]*m
      B_cp[j] += B_cp[i]*m

  return A_cp, B_cp

In [10]:
A = np.array([[1,1,1],[4,4,2],[2,1,-1]], dtype='float')
B = np.array([1,2,0], dtype='float').reshape(3,1)

a, b = gauss_elimination(A,B)
x = solve_system_ts(a,b)
x

<ipython-input-9-3cb131564d52>:10: RuntimeWarning: divide by zero encountered in double_scalars
  m = (-1)*A_cp[j,i]/A_cp[i,i]
<ipython-input-9-3cb131564d52>:11: RuntimeWarning: invalid value encountered in multiply
  A_cp[j,:] += A_cp[i,:]*m
<ipython-input-4-ec240ba048bc>:8: RuntimeWarning: invalid value encountered in divide
  x[i] = b_cp[i]/A[i,i]


array([nan, nan, nan])